spring:
  application:
    name: "app-A-enterprise"
    
management:
  endpoints:
    web:
      exposure:
        include: "refresh, bus-refresh, beans, env"

heading:
  level: "zero"
  font: "Helvetica"
  size: 12
